### ISSUE TITLE
eos vs ethereum vs bitcoin for persisting hashes

### ISSUE THREAD

**Issue by ntheile** [ntheile/blockusign#24]
pros and cons

**Comment by friedger** [comment]
For eos, there is eosproof.io already, you could hook into that contract...

**Comment by ntheile** [comment]
thanks @friedger , im thinking about staying in the blockstack/bitcoin ecosystem for now and looking into OP_RETURN in bitcoin since a users public key with the blockstack attestations can be more of a proof of a "real user".  https://forum.blockstack.org/t/prove-two-parties-signed-a-copy-of-a-document-multi-sig-hash-op-return/6107 .

 I was going down the EOS path and still find it very interesting, but after doing some market research i found many people are willing to pay higher fee's and transaction times to persist the hash on bitcoin.

**Comment by ntheile** [comment]
another notable chain is Factom

**Comment by ntheile** [comment]
using bitcoin blockchain for persisting hashes. it is Economical using the Blockstack Subdomains and batching hashes.
