### ISSUE TITLE
Drag & drop problem when signing a document

### ISSUE THREAD

**Issue by altuncu** [ntheile/blockusign#35]
When signing a document, generally, the bottom of the last page is signed. However, it is not possible to sign an empty place at the bottom since blue dotted lines show the end of the document as the last line in the document.

**Comment by ntheile** [comment]
yeah i think it has to do with the height calculcation for the SVG overlay. I'll take a look at it

**Comment by ntheile** [comment]
commenting out these lines might fix it.... i will test soon

dragOn.js

line 613-614

```
ondragleave: function (event) {
    // remove the drop feedback style
     event.target.classList.remove("drop-target");
    //event.relatedTarget.classList.remove("drag-can-drop");
    //event.relatedTarget.textContent = "Dragged out";
},
```

**Comment by ntheile** [comment]
fixed
https://github.com/ntheile/blockusign/commit/1a68d6f595c26dd65e9ca98b06a28dbca3199fb0
