### ISSUE TITLE
Safari Integration

### ISSUE THREAD

**Issue by altuncu** [ntheile/blockusign#36]
Many users are using Safari as a web browser. However, Blockusign doesn't work on Safari in Mac. Please, improve it to support Safari also.

**Comment by ntheile** [comment]
is it the blockstack login that does not work?

**Comment by altuncu** [comment]
Even the website can't be accessed. I tried on Chrome and it worked but didn't work on Safari.

**Comment by ntheile** [comment]
most of the safari bugs are fixed, such as login. login still does not work in a local debug environment but works when deployed to a server with https
