### ISSUE TITLE
Error going to signup page - screenshot attached

### ISSUE THREAD

**Issue by wileyj** [ntheile/blockusign#80]
<img width="758" alt="screen shot 2019-02-06 at 10 28 41" src="https://user-images.githubusercontent.com/2847772/52352157-1a38be80-29fa-11e9-8ebb-3b27db07be62.png">

**Comment by ntheile** [comment]
Thanks for reporting this! I setup continuous deployment and the swap from staging to prod broke something. It should be fixed now
