### ISSUE TITLE
Cant login issue below after I click approve

### ISSUE THREAD

**Issue by MedBTG** [ntheile/blockusign#81]
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by ntheile** [comment]
There was an issue with the blockusign logo. I think this fixed it https://github.com/ntheile/blockusign/commit/b16c3ad36609d24efb701a7598c67e9c1064e232

**Comment by MedBTG** [comment]
Still recieve this 
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by ntheile** [comment]
I updated blockstack.js to 18.3.0 but the protocol handler still acts goofy sometimes. 

Are you experiencing the issue on the hosted site https://blockusign.co or when running it locally at https://localhost:8100 ?

**Comment by MedBTG** [comment]
Happens in both.  And also if I try to go to blockusign from graphite.  I get a spinning logo forever

**Comment by ntheile** [comment]
Blockstack login stores some data in localstorage, i wonder if that became corrupted. On https://blockusign.co/index.html can you clear all cookies and localstorage? In chrome,  I typically go to developer tools > application (tab) >clear storage (menu) > check all the boxes > clear site data.

**Comment by MedBTG** [comment]
Looks like it was a chrome cache issue.  thx
