### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by jimblue** [ntheile/blockusign#91]
Hi,

I'm getting the following error on login:

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by ntheile** [comment]
Hey @jimblue thanks for reporting!

It appeared to be an issue with the query string being over the limit of the hosting provider (azure). I am not sure if something changed on the blockstack side (maybe they are sending more data back in the authResponse) or possibly Azure (my hosting provider) changed a limit on the size of data coming back in the url. 

The issue should be resolved now. I increased the query string limit on my azure web.config file:
```
<system.web>
      <httpRuntime maxQueryStringLength="8192" requestPathInvalidCharacters="" enableVersionHeader="false" relaxedUrlToFileSystemMapping="true" />
</system.web>
<system.webServer>
      <security>
            <requestFiltering allowDoubleEscaping="true">
            <requestLimits maxQueryString="8192" />
        </requestFiltering>
</security>
```
